services:
  gamehost:
    build: .
    container_name: gamehost
    ports:
      - "${FRONTEND_PORT}:3000"
      - "${BACKEND_PORT}:8000"
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    entrypoint: sh entrypoint.sh
    env_file: .env
