"""empty message

Revision ID: b05ebaceec6e
Revises: ecf074adb149
Create Date: 2025-10-08 20:51:41.248977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b05ebaceec6e'
down_revision: Union[str, Sequence[str], None] = 'ecf074adb149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'farrar142/mvix'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
